name: "Setup Docker"

inputs:
  username:
    description: "Username"
    required: true
  password:
    description: "Password"
    required: true
  ghcr_username:
    description: "GHCR username. Usually set from the github.actor variable"
    required: true
  ghcr_password:
    description: "GHCR password. Usually set from the secrets.GITHUB_TOKEN variable"
    required: true
  sha:
    description: "Commit Used To Build The Images"
    required: false
    default: ''

outputs:
  sha_short:
    description: "The short SHA used for image builds"
    value: ${{ steps.vars.outputs.sha_short }}

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        # Pinning v0.9.1 for Buildx and BuildKit v0.10.6
        # BuildKit v0.11 which has a bug causing intermittent 
        # failures pushing images to GHCR
        version: v0.9.1
        driver-opts: image=moby/buildkit:v0.10.6

    - name: Login to DockerHub
      if: ${{ github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name == 'release' || github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch' || github.event_name == 'repository_dispatch' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.ghcr_username }}
        password: ${{ inputs.ghcr_password }}
